import app.robot.sindarin_dictionary_en.Plugins
import app.robot.sindarin_dictionary_en.Versions

buildscript {
    ext {
        composeCompilerVersion = "${Versions.kotlin}"
        composeCompiler = "${Plugins.composeCompiler}"
    }
}
apply plugin: Plugins.library
apply plugin: Plugins.kotlinAndroid

apply from: "$rootDir/config/dependencies-groups.gradle"
apply from: "$rootDir/config/config-android.gradle"
apply from: "$rootDir/config/config-product-flavors.gradle"

android {
    namespace 'apps.robot.sindarin_dictionary_en.base_ui'
    productFlavors {
        EngFree {
            minSdkVersion 24
            def appodealAppKey = providers.gradleProperty("appodealAppKey").getOrElse("")
            buildConfigField "String", "APPODEAL_APP_KEY", "\"${appodealAppKey}\""
        }
    }
}

dependencies {
    composeCore()
    support()
    navigationCompose()
    koin()
    kotlinLib()
    EngFreeImplementation "com.appodeal.ads.sdk:core:4.4.0"
    EngFreeImplementation "com.appodeal.ads.sdk.adapters:admob:25.2.0.0"
}
